const data = require('./nodes/Alist/resource/driver_spaces/index.json')
const _ = require('lodash')

const cloudData = {
  "115 Cloud": "115云盘",
  "115 Open": "115开放平台",
  "115 Share": "115分享",
  "123Pan": "123网盘",
  "123PanLink": "123网盘链接",
  "123PanShare": "123网盘分享",
  "AList V2": "AList V2",
  "AList V3": "AList V3",
  "Alias": "别名",
  "Aliyundrive": "阿里云盘",
  "AliyundriveOpen": "阿里云盘开放平台",
  "AliyundriveShare": "阿里云盘分享",
  "Azure Blob Storage": "Azure Blob存储",
  "BaiduNetdisk": "百度网盘",
  "BaiduPhoto": "百度相册",
  "BaiduShare": "百度分享",
  "ChaoXingGroupDrive": "超星群组云盘",
  "Cloudreve": "Cloudreve网盘",
  "Crypt": "Crypt",
  "Doge": "多吉云",
  "Doubao": "豆包",
  "DoubaoShare": "豆包分享",
  "Dropbox": "Dropbox",
  "FTP": "FTP协议",
  "FebBox": "FebBox",
  "FeijiPan": "飞机盘",
  "GitHub API": "GitHub API",
  "GitHub Releases": "GitHub Releases",
  "GoogleDrive": "Google云端硬盘",
  "GooglePhoto": "Google相册",
  "HalalCloud": "HalalCloud",
  "ILanZou": "蓝奏云国际版",
  "IPFS API": "IPFS API",
  "KodBox": "可道云",
  "Lanzou": "蓝奏云",
  "Lark": "飞书云",
  "LenovoNasShare": "联想NAS分享",
  "Local": "本地存储",
  "MediaTrack": "媒体追踪",
  "Mega_nz": "Mega网盘",
  "Misskey": "Misskey",
  "MoPan": "魔盘",
  "NeteaseMusic": "网易云音乐",
  "Onedrive": "微软OneDrive",
  "Onedrive Sharelink": "OneDrive分享链接",
  "OnedriveAPP": "OneDrive应用",
  "PikPak": "PikPak",
  "PikPakShare": "PikPak分享",
  "Quark": "夸克网盘",
  "QuarkTV": "夸克TV",
  "Quqi": "曲奇云盘",
  "S3": "AWS S3",
  "SFTP": "SFTP协议",
  "SMB": "SMB协议",
  "Seafile": "Seafile",
  "Teambition": "Teambition网盘",
  "Terabox": "Terabox",
  "Thunder": "迅雷",
  "ThunderBrowser": "迅雷浏览器",
  "ThunderBrowserExpert": "迅雷浏览器专家版",
  "ThunderExpert": "迅雷专家版",
  "ThunderX": "迅雷X",
  "ThunderXExpert": "迅雷X专家版",
  "Trainbit": "Trainbit",
  "UC": "UC网盘",
  "UCTV": "UC TV",
  "USS": "USS协议",
  "UrlTree": "链接树",
  "VTencent": "腾讯微云",
  "Virtual": "虚拟存储",
  "WebDav": "WebDav协议",
  "WeiYun": "微云",
  "WoPan": "沃盘",
  "YandexDisk": "Yandex磁盘"
}
const allHelpFields = _.uniq(_.flatMap(data, (value) =>
  _.flatMap([value.common, value.additional], (arr) => _.map(arr, 'type'))
).filter((value) => !!value));


const help = {
  "The path you want to mount to, it is unique and cannot be repeated": "要挂载的路径，必须唯一且不可重复",
  "use to sort": "用于排序",
  "The cache expiration time for this storage": "该存储的缓存过期时间",
  "one of QR code token and cookie required": "需要二维码令牌或Cookie中的一种",
  "select the QR code device, default linux": "选择二维码设备，默认为linux",
  "list api per page size of 115 driver": "115网盘列表API每页大小",
  "limit all api request rate ([limit]r/1s)": "限制所有API请求速率（[limit]次/秒）",
  "limit all api request rate (1r/[limit_rate]s)": "限制所有API请求速率（1次/[limit_rate]秒）",
  "share code of 115 share link": "115分享链接的分享码",
  "receive code of 115 share link": "115分享链接的接收码",
  "structure:FolderName:\n  [FileSize:][Modified:]Url": "结构：文件夹名:\n  [文件大小:][修改时间:]URL",
  "minutes": "分钟",
  "Need to enable proxy": "需要启用代理",
  "0 for auto": "0表示自动",
  "Enable to report the real file size during upload": "启用上传时报告真实文件大小",
  "Enable to use large thumbnail for images": "启用使用大缩略图",
  "Fill in the cookie if need captcha": "如需验证码请填写Cookie",
  "1<=thread<=32": "1<=线程数<=32",
  "Protects same-name files from Delete or Rename": "保护同名文件不被删除或重命名",
  "Need to enable proxy. Unit: KB": "需要启用代理。单位：KB",
  "Keep it empty if you don't have one": "如果没有请留空",
  "If you enable this option, the file will be uploaded to the server first, so the progress will be incorrect": "启用此选项后文件将先上传至服务器，因此进度显示会不准确",
  "If you are using Aliyun ECS is located in Beijing, you can turn it on to boost the upload speed": "如果使用位于北京的阿里云ECS，可开启以提升上传速度",
  "e.g. https://accountname.blob.core.windows.net/. The full endpoint URL for Azure Storage, including the unique storage account name (3 ~ 24 numbers and lowercase letters only).": "例如 https://accountname.blob.core.windows.net/。Azure存储的完整端点URL，包含唯一的存储账户名（仅3~24位数字和小写字母）",
  "The access key for Azure Storage, used for authentication. https://learn.microsoft.com/azure/storage/common/storage-account-keys-manage": "Azure存储访问密钥，用于认证",
  "The name of the container in Azure Storage (created in the Azure portal). https://learn.microsoft.com/azure/storage/blobs/blob-containers-portal": "Azure存储中的容器名称（在Azure门户中创建）",
  "The expiration time for SAS URLs, in hours.": "SAS URL的过期时间（小时）",
  "This is where the encrypted data stores": "加密数据存储位置",
  "the main password": "主密码",
  "If you don't know what is salt, treat it as a second password. Optional but recommended": "如果不了解salt，可视为第二密码（可选但推荐）",
  "for advanced user only! encrypted files will have this suffix": "仅限高级用户！加密文件将添加此后缀",
  "for advanced user only!": "仅限高级用户！",
  "enable thumbnail which pre-generated under .thumbnails folder": "启用预生成在.thumbnails文件夹中的缩略图",
  "show hidden directories and files": "显示隐藏目录和文件",
  "Remove bucket name from path when using custom host.": "使用自定义主机时从路径中移除桶名",
  "Add filename to Content-Disposition header.": "将文件名添加到Content-Disposition头",
  "list api per page size of FebBox driver": "飞盒云驱动每页列表API大小",
  "user ip address for download link which can speed up the download": "用户IP地址（可加速下载链接）",
  "A branch, a tag or a commit SHA, main branch by default.": "分支、标签或提交SHA（默认主分支）",
  "GitHub proxy, e.g. https://ghproxy.net/raw.githubusercontent.com or https://gh-proxy.com/raw.githubusercontent.com": "GitHub代理（如 https://ghproxy.net/raw.githubusercontent.com）",
  "structure:[path:]org/repo": "结构：[路径:]组织/仓库",
  "show README、LICENSE file": "显示README、LICENSE文件",
  "GitHub token, if you want to access private repositories or increase the rate limit": "GitHub令牌（用于访问私有仓库或提高速率限制）",
  "show all versions": "显示所有版本",
  "GitHub proxy, e.g. https://ghproxy.net/github.com or https://gh-proxy.com/github.com ": "GitHub代理（如 https://ghproxy.net/github.com）",
  "such as: folder,name,modifiedTime": "例如：folder,name,modifiedTime",
  "chunk size while uploading (unit: MB)": "上传分块大小（单位：MB）",
  "login type is refresh_token,this is required": "登录类型为refresh_token时必填",
  "1 <= thread <= 32": "1 <= 线程数 <= 32",
  "about 15 days valid, ignore if shareUrl is used": "约15天有效期（使用shareUrl时可忽略）",
  "basic URL for file operation": "文件操作基础URL",
  "used to get the sharing page": "用于获取分享页面",
  "To use webdav, you need to enable it": "使用WebDAV需先启用",
  "app id": "应用ID",
  "app secret": "应用密钥",
  "external mode": "外部模式",
  "tenant url prefix": "租户URL前缀",
  "The part after the last / in the shared link": "分享链接中最后一个/后的部分",
  "The password of the shared link": "分享链接密码",
  "You can change it to your local area network": "可更改为本地网络地址",
  "enable thumbnail": "启用缩略图",
  "Number of concurrent thumbnail generation goroutines. This controls how many thumbnails can be generated in parallel.": "并发生成缩略图的goroutine数量（控制并行生成缩略图的数量）",
  "The position of the video thumbnail. If the value is a number (integer ot floating point), it represents the time in seconds. If the value ends with '%', it represents the percentage of the video duration.": "视频缩略图位置（数值表示秒数，带%表示视频时长百分比）",
  "path to recycle bin, delete permanently if empty or keep 'delete permanently'": "回收站路径（留空或保留'delete permanently'表示永久删除）",
  "2FA 6-digit code, filling in the 2FA code alone will not support reloading driver": "2FA六位数验证码（仅填写2FA码不支持重载驱动）",
  "2FA secret": "2FA密钥",
  "input 'send' send sms ": "输入'send'发送短信",
  "only get 200 songs by default": "默认仅获取200首歌曲",
  "Custom host for onedrive download link": "OneDrive下载链接自定义主机",
  "don't edit'": "请勿编辑",
  "Cookie can be used on multiple clients at the same time": "Cookie可同时在多个客户端使用",
  "If you enable this option, the download speed can be increased, but there will be some performance loss": "启用此选项可提高下载速度，但会有性能损失",
  "credit key,used for login": "登录用凭证密钥",
  "login type is user,this is required": "登录类型为user时必填",
  "super safe password": "超级安全密码",
  "sign type is algorithms,this is required": "签名类型为algorithms时必填",
  "sign type is captcha_sign,this is required": "签名类型为captcha_sign时必填",
  "structure:FolderName:\n  [FileName:][FileSize:][Modified:]Url": "结构：文件夹名:\n  [文件名:][文件大小:][修改时间:]URL",
  "Use head method to get file size, but it may be failed.": "使用HEAD方法获取文件大小（可能失败）",
  "4<=thread<=32": "4<=线程数<=32",
  "Keep it empty if you want to use your personal drive": "如需使用个人网盘请留空"
}

const displyayName = {
  "mount_path": "挂载路径",
  "order": "排序",
  "remark": "备注",
  "cache_expiration": "缓存过期时间",
  "web_proxy": "网页代理",
  "webdav_policy": "WebDAV策略",
  "down_proxy_url": "下载代理URL",
  "extract_folder": "解压文件夹",
  "disable_index": "禁用索引",
  "enable_sign": "启用签名",
  "cookie": "Cookie",
  "qrcode_token": "二维码令牌",
  "qrcode_source": "二维码来源",
  "page_size": "每页大小",
  "limit_rate": "限速",
  "root_folder_id": "根文件夹ID",
  "refresh_token": "刷新令牌",
  "order_by": "排序字段",
  "order_direction": "排序方向",
  "share_code": "分享码",
  "receive_code": "接收码",
  "username": "用户名",
  "password": "密码",
  "origin_urls": "原始URL",
  "private_key": "私钥",
  "uid": "用户ID",
  "valid_duration": "有效时长",
  "sharekey": "分享密钥",
  "sharepassword": "分享密码",
  "accesstoken": "访问令牌",
  "proxy_range": "代理范围",
  "authorization": "授权",
  "type": "类型",
  "cloud_id": "云ID",
  "custom_upload_part_size": "自定义上传分块大小",
  "report_real_size": "报告真实大小",
  "use_large_thumbnail": "使用大缩略图",
  "validate_code": "验证码",
  "family_id": "家庭组ID",
  "upload_method": "上传方法",
  "upload_thread": "上传线程数",
  "family_transfer": "家庭组传输",
  "rapid_upload": "极速上传",
  "no_use_ocr": "不使用OCR",
  "root_folder_path": "根文件夹路径",
  "url": "URL",
  "access_token": "访问令牌",
  "meta_password": "元数据密码",
  "token": "令牌",
  "pass_ua_to_upsteam": "传递UA到上游",
  "forward_archive_requests": "转发归档请求",
  "paths": "路径",
  "protect_same_name": "保护同名文件",
  "download_concurrency": "下载并发数",
  "download_part_size": "下载分块大小",
  "writable": "可写",
  "internal_upload": "内部上传",
  "drive_type": "驱动类型",
  "oauth_token_url": "OAuth令牌URL",
  "client_id": "客户端ID",
  "client_secret": "客户端密钥",
  "remove_way": "移除方式",
  "livp_download_format": "LIVP下载格式",
  "share_id": "分享ID",
  "share_pwd": "分享密码",
  "endpoint": "端点",
  "access_key": "访问密钥",
  "container_name": "容器名称",
  "sign_url_expire": "签名URL过期时间",
  "download_api": "下载API",
  "custom_crack_ua": "自定义破解UA",
  "upload_api": "上传API",
  "low_bandwith_upload_mode": "低带宽上传模式",
  "only_list_video_file": "仅列出视频文件",
  "show_type": "显示类型",
  "album_id": "相册ID",
  "delete_origin": "删除原始文件",
  "surl": "短URL",
  "pwd": "密码",
  "BDUSS": "百度BDUSS",
  "user_name": "用户名",
  "bbsid": "论坛ID",
  "address": "地址",
  "custom_ua": "自定义UA",
  "enable_thumb_and_folder_size": "启用缩略图和文件夹大小",
  "filename_encryption": "文件名加密",
  "directory_name_encryption": "目录名加密",
  "remote_path": "远程路径",
  "salt": "盐值",
  "encrypted_suffix": "加密后缀",
  "filename_encoding": "文件名编码",
  "thumbnail": "缩略图",
  "show_hidden": "显示隐藏",
  "bucket": "存储桶",
  "region": "区域",
  "access_key_id": "访问密钥ID",
  "secret_access_key": "秘密访问密钥",
  "session_token": "会话令牌",
  "custom_host": "自定义主机",
  "enable_custom_host_presign": "启用自定义主机预签名",
  "placeholder": "占位符",
  "force_path_style": "强制路径样式",
  "list_object_version": "列出对象版本",
  "remove_bucket": "移除存储桶",
  "add_filename_to_disposition": "添加文件名到Content-Disposition",
  "share_ids": "分享ID列表",
  "encoding": "编码",
  "sort_rule": "排序规则",
  "user_ip": "用户IP",
  "ip": "IP地址",
  "owner": "所有者",
  "repo": "仓库",
  "ref": "引用",
  "gh_proxy": "GitHub代理",
  "gpg_private_key": "GPG私钥",
  "gpg_key_passphrase": "GPG密钥密码",
  "committer_name": "提交者名称",
  "committer_email": "提交者邮箱",
  "author_name": "作者名称",
  "author_email": "作者邮箱",
  "mkdir_commit_message": "创建目录提交消息",
  "delete_commit_message": "删除提交消息",
  "put_commit_message": "上传提交消息",
  "rename_commit_message": "重命名提交消息",
  "copy_commit_message": "复制提交消息",
  "move_commit_message": "移动提交消息",
  "repo_structure": "仓库结构",
  "show_readme": "显示README",
  "show_all_version": "显示所有版本",
  "chunk_size": "分块大小",
  "show_archive": "显示归档",
  "app_id": "应用ID",
  "app_version": "应用版本",
  "app_secret": "应用密钥",
  "mode": "模式",
  "gateway": "网关",
  "account": "账户",
  "share_password": "分享密码",
  "baseUrl": "基础URL",
  "shareUrl": "分享URL",
  "user_agent": "用户代理",
  "repair_file_info": "修复文件信息",
  "external_mode": "外部模式",
  "tenant_url_prefix": "租户URL前缀",
  "host": "主机",
  "thumb_cache_folder": "缩略图缓存文件夹",
  "thumb_concurrency": "缩略图并发数",
  "video_thumb_pos": "视频缩略图位置",
  "mkdir_perm": "创建目录权限",
  "recycle_bin_path": "回收站路径",
  "project_id": "项目ID",
  "order_desc": "降序排序",
  "email": "邮箱",
  "two_fa_code": "两步验证码",
  "two_fa_secret": "两步验证密钥",
  "phone": "电话",
  "sms_code": "短信验证码",
  "device_info": "设备信息",
  "song_limit": "歌曲限制",
  "is_sharepoint": "是否SharePoint",
  "redirect_uri": "重定向URI",
  "site_id": "站点ID",
  "tenant_id": "租户ID",
  "platform": "平台",
  "captcha_token": "验证码令牌",
  "device_id": "设备ID",
  "disable_media_link": "禁用媒体链接",
  "use_transcoding_address": "使用转码地址",
  "query_token": "查询令牌",
  "cdn": "CDN",
  "passphrase": "密码短语",
  "ignore_symlink_error": "忽略符号链接错误",
  "share_name": "分享名称",
  "repoId": "仓库ID",
  "repoPwd": "仓库密码",
  "use_s3_upload_method": "使用S3上传方法",
  "credit_key": "信用密钥",
  "safe_password": "安全密码",
  "use_video_url": "使用视频URL",
  "login_type": "登录类型",
  "sign_type": "签名类型",
  "algorithms": "算法",
  "captcha_sign": "验证码签名",
  "timestamp": "时间戳",
  "client_version": "客户端版本",
  "package_name": "包名",
  "download_user_agent": "下载用户代理",
  "AUSHELLPORTAL": "AUSHELL门户",
  "apikey": "API密钥",
  "operator_name": "操作员名称",
  "operator_password": "操作员密码",
  "anti_theft_chain_token": "防盗链令牌",
  "url_structure": "URL结构",
  "head_size": "头部大小",
  "tf_uid": "TF用户ID",
  "num_file": "文件数量",
  "num_folder": "文件夹数量",
  "max_file_size": "最大文件大小",
  "min_file_size": "最小文件大小",
  "vendor": "供应商",
  "tls_insecure_skip_verify": "跳过TLS不安全验证",
  "cookies": "Cookies"
}
const type = {
  'string': 'string',
  'number': 'number',
  'bool': 'boolean',
  'text': 'string',
  'float': 'number',
  'select': 'options'
}
const query = _.flatMap(data, (v, k) => {
  const query = _.flatMap([v.common, v.additional], (arr) => {
    return arr.map(it => {

      return {
        ...it,
        ...(it.type == 'select' ? it.options.split(',').map(it => {
          return {
            name: it,
            value: it
          }
        }) : {}),
        typeOptions: {
          show: {
            driver: k
          }
        },
        displyayName: displyayName[it.name],
        name: it.name,
        type: type[it.type],
        description: help[it.help]
      }
    })
  })
  return query
})
console.log(query)
